on:
  # Trigger analysis when pushing in master or pull requests, and when creating
  # a pull request.
  push:
    branches:
      - master
      - dev
    tags:
      - '*'
  pull_request:
      types: [opened, synchronize, reopened]
name: Main Workflow
jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
      with:
        projectBaseDir: .
        args: >
          -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.organization=sm-hieunv3
          -Dsonar.projectKey=sm-hieunv3_calculator
          -Dsonar.projectName=calculator
          -Dsonar.sources=api,public
          -Dsonar.verbose=true
